apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: people-service-ing
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /people
        pathType: Prefix
        backend:
          service:
            name: people-service
            port:
              number: 8080
